openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: solid-spoon
  url: http://83.212.100.226:3001/v1
security:
- {}
tags:
- description: not yet ready
  name: proj
paths:
  /proj:
    post:
      operationId: createproj
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/proj'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/proj'
          description: successful operation
      summary: Creates the data
      tags:
      - proj
      x-eov-operation-handler: controllers/ProjController
  /proj/{projId}:
    delete:
      operationId: deleteproj
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: projId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - proj
      x-eov-operation-handler: controllers/ProjController
    get:
      operationId: getproj
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: projId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/proj'
          description: successful operation
      summary: Get the element
      tags:
      - proj
      x-eov-operation-handler: controllers/ProjController
    put:
      operationId: updateproj
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: projId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/proj'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/proj'
          description: successful operation
      summary: Updates the element
      tags:
      - proj
      x-eov-operation-handler: controllers/ProjController
  /proj/getAll:
    get:
      operationId: getAllproj
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/proj'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - proj
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/ProjController
components:
  schemas:
    proj:
      example:
        image: image
        _id: _id
        abstract: abstract
        title: title
      properties:
        _id:
          type: string
        title:
          type: string
        image:
          type: string
        abstract:
          type: string
      required:
      - abstract
      - image
      - title
      type: object
